# Gradle settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric toolchain (check https://fabricmc.net/develop)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.19

# Dependencies
fabric_version=0.158.0+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.1

# Mod properties
mod_version=2.2.0
maven_group=ovh.unlimitedbytes
archives_base_name=bytes-auto-sell
